export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const CHECK_CHECKBOX = 'CHECK_CHECKBOX';
export const UNCHECK_CHECKBOX = 'UNCHECK_CHECKBOX';
