// Counter
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
// Wish list
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const CHANGE_QUANTITY = 'INCREMENT_QUANTITY';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
// Filters
export const CHECK_CHECKBOX = 'CHECK_CHECKBOX';
export const RESET_FILTERS = 'RESET_FILTERS';
export const SET_PRICE_RANGE = 'SET_PRICE_RANGE';
// Products pagination
export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const CHANGE_ITEMS_NUMBER_ON_PAGE = 'CHANGE_ITEMS_NUMBER_ON_PAGE';
export const CHANGE_SORTING_ORDER = 'CHANGE_SORTING_ORDER';
export const CHANGE_ORDER_TYPE = 'CHANGE_ORDER_TYPE';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';
export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW';
export const NOTIFICATION_HIDE = 'NOTIFICATION_HIDE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const NOTIFICATION_ITEM_ADD_TO_LIST = 'NOTIFICATION_ITEM_ADD_TO_LIST';
export const NOTIFICATION_ITEM_REMOVE_FROM_LIST = 'NOTIFICATION_ITEM_REMOVE_FROM_LIST';

// Blog page
export const GET_BLOG_ITEMS_SUCCESS = 'GET_BLOG_ITEMS_SUCCESS';
export const GET_BLOG_ITEMS_ERROR = 'GET_BLOG_ITEMS_ERROR';

// Cart
export const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT';
