export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

export const CHECK_CHECKBOX = 'CHECK_CHECKBOX';

export const CHANGE_ITEMS_NUMBER_ON_PAGE = 'CHANGE_ITEMS_NUMBER_ON_PAGE';
export const CHANGE_SORTING_ORDER = 'CHANGE_SORTING_ORDER';
export const CHANGE_ORDER_TYPE = 'CHANGE_ORDER_TYPE';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const NULL_STATE_ON_PAGE_CHANGE = 'NULL_STATE_ON_PAGE_CHANGE';
